### PR TITLE
Info sharing front-end

### LINKED ISSUE #370: Info sharing: merge in complete user-facing feature
This'll involve combining the backend work of #324 (on the add-info-sharing-release-agreement branch) and the front end work of #323 and adjusting any tests as necessary.

### PR DESCRIPTION
**Pull request by alanjosephwilliams**
Touches #370, #323,  #368, #297 

- New view for info-sharing—adding in the option to choose method of contact, which we are not handling yet.
- Separate views for rights and regs + signature
- passing feature and integration tests covering the new flow
- Homepage tweaks

### CODE REVIEW

**Comment by alanjosephwilliams** [comment]
Hrm, the tests pass when I run the full suite locally 

image

**Comment by alanjosephwilliams** [comment]
thoughts on this situation @daguar?

**Comment by daguar** [comment]
@alanjosephwilliams — Looks like maybe you didn't check in the new views to git?

**Comment by alanjosephwilliams** [comment]
:+1: good catch dave, done and done.

**Comment by daguar** [comment]
Reviewing now! Quick feedback on process — I know it was probably easier to go in and implement the changes for #297 (give signature own view) and #368 (homepage nitpicks), but I'd prefer to do those in separate PRs, because it makes reviewing and merging take longer, and so potentially hold up the core of the issue being addressed here. It okay to separate things into smaller patches moving forward?

**Comment by daguar** [comment]
Edited main issue to say "touches # ..." because I don't want this to auto-close just yet (I need to add some test work.) I'll manually close those issues when done.

**Comment by alanjosephwilliams** [comment]
Absolutely. PR hygiene FTW. Continuous improvement.

On Tue, Feb 24, 2015 at 12:49 PM, Dave Guarino <notifications@github.com>
wrote:

> Merged #372 <https://github.com/codeforamerica/clean/pull/372>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/pull/372#event-241238946>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
One more piece of feedback — when you're doing implementing a new form on the front end, could you please double-check that you've edited the markup's `name` fields for the new content? Specifically:
https://github.com/codeforamerica/clean/blob/53ca8d75a28da977c50db35e33ec8db5d99a42a8/app/views/application/info_sharing.erb#L22-L32

(I know this was probably just a copy/paste issue, but just a quick reminder.)

**Comment by daguar** [comment]
(Or if you consider that in-scope for my backend work, let me know. I just want to know one way or another what the expectation is.)

**Comment by alanjosephwilliams** [comment]
yeeesh definitely thanks for flagging. 

In general, is this sort of over-the-fence approach to new user data sub-optimal?

**Comment by daguar** [comment]
Could you say a bit more about what you mean?

In general, my working assumption is that new forms coming from your end will have name fields that describe the form field well, and I will tweak as necessary to accommodate the backend (for example, I just myself changed `email` to `contact_by_email`.)

**Comment by daguar** [comment]
(But I'll give you a heads up if I change in case that affects any styling.)

**Comment by alanjosephwilliams** [comment]
That sounds good to me—what I actually need to do here is write integration tests when adding a new form element. That way, an oversight like the name of the data input will be caught before PR.

**Comment by daguar** [comment]
That's exactly what I was thinking for avoiding this in the future. It's probably in my court for now. (I may make that my tech debt payment this week.)

In this case specifically, we'll want to basically make sure that the PDF writer (`Calfresh::ApplicationWriter`) receives all the correct input given the integration test's path. I've opened an issue for that in #376.

**Comment by alanjosephwilliams** [comment]
:+1:

On Tue, Feb 24, 2015 at 1:44 PM, Dave Guarino <notifications@github.com>
wrote:

> That's exactly what I was thinking for avoiding this in the future. It's
> probably in my court for now. (I may make that my tech debt payment this
> week.)
>
> In this case specifically, we'll want to basically make sure that the PDF
> writer (Calfresh::ApplicationWriter) receives all the correct input given
> the integration test's path. I've opened an issue for that in #376
> <https://github.com/codeforamerica/clean/issues/376>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/pull/372#issuecomment-75852917>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Pull request merged**
