### PR TITLE
Align error messages with app styles

### LINKED ISSUE #360: Style parsley errors
Once #358 is merged, the last truly offensive part of our UI will be our parsley errors. We updated the copy, but the styling is still out-of-the-box-awful. Restyling them will take a little bit of care and getting up to speed with Parsley.

image

### PR DESCRIPTION
**Pull request by alanjosephwilliams**
This tidy little PR will close #360 

- authors new folder and file, `javascripts/custom/parsley-override.js`
- updates `application.js` manifest file to load that .js file before other parsley js
- updates `parsley.css` and `custom.css` to implement new styles.

### CODE REVIEW

**Comment by alanjosephwilliams** [comment]
Btw, per the example set by @bsmithgall, here is how the error messages now look. You can see the "before" look in #360. Under the hood there are changes to markup, styles, and js.

image

**Comment by daguar** [comment]
Awesome, thanks! :+1:

**Comment by daguar** [comment]
Live on all servers

**Comment by bsmithgall** [comment]
Did you mean me? Or Ben Golder?

**Comment by daguar** [comment]
You do screenshots in PRs right?

**Pull request merged**
