### PR TITLE
Add printable confirmation page, closes #355

### LINKED ISSUE #355: End with printable confirmation page
That acts as a receipt + next step reference for clients. See user Lisa for the motivation: https://github.com/codeforamerica/health/wiki/User-research#20150217-lisa-at-meda

This may be v1 of what turns into downloading a full copy of the app (https://github.com/codeforamerica/clean/issues/126)

### PR DESCRIPTION
**Pull request by alanjosephwilliams**
PR for rebased work :)

For more details, see WIP PR #537

### CODE REVIEW

**Comment by alanjosephwilliams** [comment]
@daguar travis CI build is still in progress?

**Comment by alanjosephwilliams** [comment]
@daguar bump

**Comment by daguar** [comment]
Shippin today!

**Comment by alanjosephwilliams** [comment]
@daguar bump

**Pull request merged**
