### PR TITLE
Doc upload redux styles ajw

### PR DESCRIPTION
**Pull request by alanjosephwilliams**
This PR doesn't address a specific issue, but rather one or more of the to-do list items in #365 and constitutes WIP on #410. Anyway, it includes

- Responsive styles consistent with the rest of the app for the page heading, page context copy, and the primary button for advancing to the next view.
- New, *not-yet-totally-generalized* styles for the table of uploaded documents themselves—many of which are overrides or layers on top of the out-of-the-box styles.
- This work will need to be refactored, with a more thoughtful, (probably through pairing with @daguar ) approach to removing dependencies on third-party styles that came along with the module. For now though, we want to impact the WIP implementation as little as possible.

### CODE REVIEW

**Comment by alanjosephwilliams** [comment]
The order of the commit log makes me think I've submitted this PR incorrectly.

**Comment by daguar** [comment]
> The order of the commit log makes me think I've submitted this PR incorrectly.

It looks like you might have branched off of master and merged the `doc-upload-redux` branch into that, rather than branching off of `doc-upload-redux`? (I'm looking at https://github.com/codeforamerica/clean/commit/79b4cd858fce56af06b5e93ea5dcffd65ad389a6 and the history here: https://github.com/codeforamerica/clean/commits/doc-upload-redux-styles-ajw )

I tried to do a rebase just now but hit a lot of conflicts; when we're both in the office let's sit down and try and figure it out. I think the best approach might be to squash your work on this branch into a single commit and `git cherry pick` it over to a new branch branched off of doc-upload-redux but I might want to get review by someone else beforehand.

**Comment by alanjosephwilliams** [comment]
:+1:

On Thu, Apr 9, 2015 at 8:56 AM, Dave Guarino <notifications@github.com>
wrote:

> The order of the commit log makes me think I've submitted this PR
> incorrectly.
>
> It looks like you might have branched off of master and merged the
> doc-upload-redux branch into that, rather than branching off of
> doc-upload-redux? (I'm looking at 79b4cd8
> <https://github.com/codeforamerica/clean/commit/79b4cd858fce56af06b5e93ea5dcffd65ad389a6>
> and the history here:
> https://github.com/codeforamerica/clean/commits/doc-upload-redux-styles-ajw
> )
>
> I tried to do a rebase just now but hit a lot of conflicts; when we're
> both in the office let's sit down and try and figure it out. I think the
> best approach might be to squash your work on this branch into a single
> commit and git cherry pick it over to a new branch branched off of
> doc-upload-redux but I might want to get review by someone else beforehand.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/clean/pull/476#issuecomment-91271886>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by daguar** [comment]
Closing this because the commits are contained in #484

**Pull request closed without merging**
