### PR TITLE
add google analytics tracking snippet

### LINKED ISSUE #409: Setup Google Analytics

### PR DESCRIPTION
**Pull request by lippytak**
Closes #409. This is on the CfA account with Property = 'CleanAssist'

### CODE REVIEW

**Comment by daguar** [comment]
I'd like to maybe make this an environment variable so that we have diff for demo/prod. Could you do that?

**Comment by lippytak** [comment]
Good call will do and update this PR. Issue: #449

**Comment by daguar** [comment]
:+1: Closing until that's ready — please re-open at that point! :D

**Comment by lippytak** [comment]
Rather than setting up multiple properties for multiple environments, I think the easiest way to deal with this is to create a View Filter that only includes data from our production domain, [as suggested on SO](http://stackoverflow.com/questions/1251922/is-there-a-way-to-stop-google-analytics-counting-development-work-as-hits):
screen shot 2015-03-29 at 2 26 30 pm

I tested this on dev:
- No filter > view the site > confirm that GA shows 1 active user
- Add filter > view the site > confirm that GA shows 0 active users

:+1: LMK if you think there's a strong reason to also log demo and/or log demo separately. Seems pretty low value right now.

**Comment by daguar** [comment]
:+1:

**Comment by daguar** [comment]
Live on demo + production

**Pull request merged**
